// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_Baird.Models;

#nullable disable

namespace Mission06_Baird.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Mission06_Baird.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new { CategoryId = 1, CategoryName = "Action" },
                        new { CategoryId = 2, CategoryName = "Comedy" },
                        new { CategoryId = 3, CategoryName = "Drama" },
                        new { CategoryId = 4, CategoryName = "Family" },
                        new { CategoryId = 5, CategoryName = "Horror" },
                        new { CategoryId = 6, CategoryName = "Sci-Fi" },
                        new { CategoryId = 7, CategoryName = "Thriller" },
                        new { CategoryId = 8, CategoryName = "Romance" },
                        new { CategoryId = 9, CategoryName = "Documentary" },
                        new { CategoryId = 10, CategoryName = "Animation" },
                        new { CategoryId = 11, CategoryName = "Musical" },
                        new { CategoryId = 12, CategoryName = "Western" },
                        new { CategoryId = 13, CategoryName = "Disney" },
                        new { CategoryId = 14, CategoryName = "Adventure" },
                        new { CategoryId = 15, CategoryName = "Fantasy" });
                });

            modelBuilder.Entity("Mission06_Baird.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CopiedToPlex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 6,
                            CopiedToPlex = false,
                            Director = "Christopher Nolan",
                            Edited = false,
                            LentTo = "",
                            Notes = "Wow",
                            Rating = "PG-13",
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 3,
                            CopiedToPlex = true,
                            Director = "Frank Darabont",
                            Edited = true,
                            LentTo = "Joel",
                            Notes = "Classic",
                            Rating = "R",
                            Title = "The Shawshank Redemption",
                            Year = 1994
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 1,
                            CopiedToPlex = false,
                            Director = "Christopher Nolan",
                            Edited = false,
                            LentTo = "",
                            Notes = "Batman",
                            Rating = "PG-13",
                            Title = "The Dark Knight",
                            Year = 2008
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 13,
                            CopiedToPlex = false,
                            Director = "Chris Buck and Jennifer Lee",
                            Edited = false,
                            Rating = "PG",
                            Title = "Frozen",
                            Year = 2013
                        });
                });

            modelBuilder.Entity("Mission06_Baird.Models.Movie", b =>
                {
                    b.HasOne("Mission06_Baird.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
